# Generated by Django 5.2.7 on 2025-10-24 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Matches'},
        ),
    ]
