# Generated by Django 6.0 on 2025-12-19 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0002_alter_match_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='is_full',
        ),
        migrations.AlterField(
            model_name='match',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='match',
            name='mode',
            field=models.CharField(choices=[('1v1', '1 vs 1'), ('2v2', '2 vs 2')], max_length=3),
        ),
        migrations.AlterField(
            model_name='match',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='matches_joined', to=settings.AUTH_USER_MODEL),
        ),
    ]
