# Generated by Django 5.2.7 on 2025-10-26 08:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_email_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Rata-rata rating pengguna', max_digits=3),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='', help_text='Deskripsi singkat tentang diri pengguna'),
        ),
        migrations.AddField(
            model_name='profile',
            name='joined_date',
            field=models.DateField(default=django.utils.timezone.now, editable=False, help_text='Tanggal pengguna bergabung'),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_booking',
            field=models.PositiveIntegerField(default=0, help_text='Jumlah booking yang pernah dilakukan'),
        ),
    ]
