# Generated by Django 5.2.7 on 2025-10-23 08:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_remove_field_user_vendor_field_vendor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="field",
            name="vendor",
        ),
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("contact", models.CharField(blank=True, max_length=50)),
                ("address", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("facilities", models.TextField(blank=True)),
                ("photo_url", models.URLField(blank=True)),
                ("price_per_hour", models.PositiveIntegerField(default=0)),
                ("is_available", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.vendor",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Booking",
        ),
    ]
