# Generated by Django 5.2.7 on 2025-10-23 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_remove_field_vendor_venue_delete_booking"),
        ("review", "0002_remove_review_field_review_venue"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Field",
        ),
    ]
