# Generated by Django 5.2.7 on 2025-10-23 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_remove_field_vendor_venue_delete_booking"),
        ("review", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="field",
        ),
        migrations.AddField(
            model_name="review",
            name="venue",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="main.venue",
            ),
            preserve_default=False,
        ),
    ]
