# Generated by Django 5.2.7 on 2025-10-23 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        ('review', '0002_remove_review_field_review_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='booking.venue'),
        ),
    ]
