# Generated by Django 5.2.7 on 2025-10-24 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_field'),
        ('review', '0003_alter_review_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main.venue'),
        ),
    ]
