# Generated by Django 5.2.7 on 2025-10-24 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_lapanganpadel_options_and_more'),
        ('review', '0004_alter_review_venue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='venue',
        ),
        migrations.AddField(
            model_name='review',
            name='lapangan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='home.lapanganpadel'),
            preserve_default=False,
        ),
    ]
