# Generated by Django 5.2.7 on 2025-10-24 03:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_lapanganpadel_options_and_more'),
        ('review', '0006_review_anonymous'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'lapangan')},
        ),
    ]
