# Generated by Django 5.2.7 on 2025-10-23 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LapanganPadel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place_id",
                    models.CharField(
                        help_text="Google Maps Place ID, untuk mencegah duplikat",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("nama", models.CharField(max_length=200)),
                ("alamat", models.CharField(max_length=300)),
                ("rating", models.FloatField(blank=True, null=True)),
                ("total_review", models.IntegerField(blank=True, null=True)),
                (
                    "thumbnail_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
