# Generated by Django 5.2.7 on 2025-10-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lapanganpadel",
            options={
                "ordering": ["-rating", "-total_review"],
                "verbose_name": "Lapangan Padel",
                "verbose_name_plural": "Lapangan Padel",
            },
        ),
        migrations.AddField(
            model_name="lapanganpadel",
            name="is_featured",
            field=models.BooleanField(
                default=False, help_text="Tampilkan di recommended"
            ),
        ),
        migrations.AddField(
            model_name="lapanganpadel",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Catatan internal tentang lapangan ini"
            ),
        ),
    ]
