# Generated by Django 5.2.7 on 2025-11-07 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_lapanganpadel_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lapanganpadel',
            name='place_id',
            field=models.CharField(blank=True, help_text='Google Maps Place ID, untuk mencegah duplikat', max_length=255, null=True, unique=True),
        ),
    ]
